version: '3'
services:
  vheditor:
    ports:
      - 3000:3000
    build: 
      context: ui
      args:
        NEXT_PUBLIC_SPARQL_ENDPOINT: https://kgrc4si.ml/graph/repositories/KGRC4SIv01 # SPARQL Endpoint接続先URL
        NEXT_PUBLIC_API_URL: http://localhost:8080 # virtualhome apiのURL
